language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
jobs:
  include:
    - name: "Python 3.6 on MacOS"
      os: osx
      osx_image: xcode9.4
      language: shell
      env:
        - TRAVIS_PYTHON_VERSION="3.6"
      before_install:
        - python3 --version
    - name: "Python 3.7 on MacOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      env:
        - TRAVIS_PYTHON_VERSION="3.7"
      before_install:
        - python3 --version
    - name: "Python 3.8 on MacOS"
      os: osx
      osx_image: xcode11.4
      language: shell
      env:
        - TRAVIS_PYTHON_VERSION="3.8"
      before_install:
        - python3 --version
  allow_failures:
    - python: "3.9-dev"
install:
  - python3 -m pip install -U pip
  - python3 -m pip install tox-travis
script: tox
