language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
jobs:
  include:
    # there seem to be no reliable way to know the pick a python version for
    # MacOS, the following settings may no longer work in the futur
    - &macos
      os: osx
      osx_image: xcode11.4
      language: shell
      before_install:
        - python3 --version
      name: Python 3.6 on MacOS
      env:
        - TRAVIS_PYTHON_VERSION=3.6
      addons:
        homebrew:
          packages:
            - python3.6
    - <<: *macos
      name: Python 3.7 on MacOS
      env:
        - TRAVIS_PYTHON_VERSION=3.7
      addons:
        homebrew:
          packages:
            - python3.7
    - <<: *macos
      name: Python 3.8 on MacOS
      env:
        - TRAVIS_PYTHON_VERSION=3.8
      addons:
        homebrew:
          packages:
            - python3.8
  allow_failures:
    - python: 3.9-dev
install:
  - python3 -m pip install -U pip
  - python3 -m pip install tox-travis
script: tox
