name: Tests

on:
  push:
    paths-ignore:
      - "*.rst"
      - "LICENSE**"
      - ".gitignore"
  pull_request:
    paths-ignore:
      - "*.rst"
      - "LICENSE**"
      - ".gitignore"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.os == 'windows-latest' }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tox
        if: ${{ matrix.os != 'windows-latest' }}
        # Run tox using the version of Python in `PATH`.
        run: |
          pip install tox
          tox -e py-coverage
      - shell: msys2 {0}
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          python -m pip install tox
          tox -e py-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          verbose: true
