name: Tests

on:
  push:
    paths-ignore:
      - "*.rst"
      - "LICENSE**"
      - ".gitignore"
  pull_request:
    paths-ignore:
      - "*.rst"
      - "LICENSE**"
      - ".gitignore"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]
        #python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Run tox
        shell: bash
        run: |
          echo $PATH
          env
          /bin/bash -h
          # Run tox using the version of Python in `PATH`.
          tox -e py-coverage -- -vv
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          verbose: true
